name: mint_core
description: Mint general project files.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  bloc: ^8.1.2
  cloud_firestore: 4.9.1
  cloud_functions: ^4.4.0
  file_picker: ^5.5.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_firebase_chat_core:
    git:
      url: https://github.com/wuffeel/flutter_firebase_chat_core.git
      ref: main
  freezed_annotation: 2.2.0
  get_it: ^7.6.4
  http: ^1.1.0
  image_picker: ^1.0.4
  injectable: ^2.3.0
  intl: 0.18.0
  json_annotation: 4.8.1
  meta: ^1.9.1
  open_filex: ^4.3.2
  path: 1.8.3
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  universal_html: ^2.2.4
  uuid: 3.0.7
  very_good_analysis: 5.1.0

dev_dependencies:
  build_runner: 2.4.6
  freezed: 2.3.5
  injectable_generator: ^2.4.0
  json_serializable: 6.7.1
  lints: ^2.0.0
  test: ^1.21.0
